#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_FRAME_POINTS_MAX        3648U
#define APP_SKIP_FIRST_ROWS         20U
#define APP_VALID_POINTS_MAX        (APP_FRAME_POINTS_MAX - APP_SKIP_FIRST_ROWS)
#define APP_DARK_ROWS               16U
#define APP_MEDIAN_WINDOW           9U
#define APP_SMOOTH_WINDOW           151U
#define APP_SMOOTH_ORDER            3U
#define APP_GROUP_COUNT_MAX         1U
#define APP_GROUP_REPLICATE_MAX     5U
#define APP_DOWNSAMPLE_STEP         16U
#define APP_DOWNSAMPLED_POINTS_MAX  ((APP_VALID_POINTS_MAX + APP_DOWNSAMPLE_STEP - 1U) / APP_DOWNSAMPLE_STEP)
#define APP_UART_RX_LINE_MAX        96U
#define APP_UART_TX_LINE_MAX        256U
#define APP_UART_IN_BAUDRATE        921600U
#define APP_UART_OUT_BAUDRATE       115200U
#define APP_NORM_Q15_SCALE          32767U

#define APP_INPUT_MODE_F103_BINARY  1U
#define APP_F103_REQUEST_12BIT_CMD  0xA1U
#define APP_F103_DEFAULT_GROUP_ID   1U
#define APP_F103_FIRST_PIXEL        0U
#define APP_F103_RX_TIMEOUT_MS      200U

#endif
